/**
  * Copyright &copy; 2012-2017 <a href="">GLAD</a> All rights reserved.
 */
package com.glad.entity;

import java.util.Date;

/**
 *
 * This model class was generated by MyBatis Generator.
 * TABLE : ODH_CODE_MANAGE
 *  2017.08.03 10:43:37
 */
public class OdhCodeManage {
    /**
     *   记录番号
     * REC_NO
     */
    private Integer recNo;

    /**
     *   属性ID
     * ATTRIB_ID
     */
    private String attribId;

    /**
     *   属性名称
     * ATTRIB_NAME
     */
    private String attribName;

    /**
     *   属性值
     * ATTRIB_VAL
     */
    private String attribVal;

    /**
     *   属性说明
     * ATTRIB_EXPLA
     */
    private String attribExpla;

    /**
     *   属性值2
     * ATTRIB_VAL2
     */
    private String attribVal2;

    /**
     *   属性说明2
     * ATTRIB_EXPLA2
     */
    private String attribExpla2;

    /**
     *   属性值3
     * ATTRIB_VAL3
     */
    private String attribVal3;

    /**
     *   属性说明3
     * ATTRIB_EXPLA3
     */
    private String attribExpla3;

    /**
     *   属性说明简称
     * ATTRIB_EXPLA_SHORT
     */
    private String attribExplaShort;

    /**
     *   登陆者工号
     * LOGIN_NO
     */
    private String loginNo;

    /**
     *   登陆者IP
     * LOGIN_IP
     */
    private String loginIp;

    /**
     *   记录作成时间
     * REC_INSERT_TIME
     */
    private Date recInsertTime;

    /**
     *   删除状态位
     * DELETE_STATE
     */
    private String deleteState;

    /**
     *   更新者工号
     * UPDATE_NO
     */
    private String updateNo;

    /**
     *   更新者IP
     * UPDATE_IP
     */
    private String updateIp;

    /**
     *   记录更新时间
     * REC_UPDATE_TIME
     */
    private Date recUpdateTime;

    /**
     * ODH_CODE_MANAGE.REC_NO
     *
     * @return the value of ODH_CODE_MANAGE.REC_NO
     */
    public Integer getRecNo() {
        return recNo;
    }

    /**
     * ODH_CODE_MANAGE.REC_NO
     *
     * @param recNo the value for ODH_CODE_MANAGE.REC_NO
     */
    public void setRecNo(Integer recNo) {
        this.recNo = recNo;
    }

    /**
     * ODH_CODE_MANAGE.ATTRIB_ID
     *
     * @return the value of ODH_CODE_MANAGE.ATTRIB_ID
     */
    public String getAttribId() {
        return attribId;
    }

    /**
     * ODH_CODE_MANAGE.ATTRIB_ID
     *
     * @param attribId the value for ODH_CODE_MANAGE.ATTRIB_ID
     */
    public void setAttribId(String attribId) {
        this.attribId = attribId;
    }

    /**
     * ODH_CODE_MANAGE.ATTRIB_NAME
     *
     * @return the value of ODH_CODE_MANAGE.ATTRIB_NAME
     */
    public String getAttribName() {
        return attribName;
    }

    /**
     * ODH_CODE_MANAGE.ATTRIB_NAME
     *
     * @param attribName the value for ODH_CODE_MANAGE.ATTRIB_NAME
     */
    public void setAttribName(String attribName) {
        this.attribName = attribName;
    }

    /**
     * ODH_CODE_MANAGE.ATTRIB_VAL
     *
     * @return the value of ODH_CODE_MANAGE.ATTRIB_VAL
     */
    public String getAttribVal() {
        return attribVal;
    }

    /**
     * ODH_CODE_MANAGE.ATTRIB_VAL
     *
     * @param attribVal the value for ODH_CODE_MANAGE.ATTRIB_VAL
     */
    public void setAttribVal(String attribVal) {
        this.attribVal = attribVal;
    }

    /**
     * ODH_CODE_MANAGE.ATTRIB_EXPLA
     *
     * @return the value of ODH_CODE_MANAGE.ATTRIB_EXPLA
     */
    public String getAttribExpla() {
        return attribExpla;
    }

    /**
     * ODH_CODE_MANAGE.ATTRIB_EXPLA
     *
     * @param attribExpla the value for ODH_CODE_MANAGE.ATTRIB_EXPLA
     */
    public void setAttribExpla(String attribExpla) {
        this.attribExpla = attribExpla;
    }

    /**
     * ODH_CODE_MANAGE.ATTRIB_VAL2
     *
     * @return the value of ODH_CODE_MANAGE.ATTRIB_VAL2
     */
    public String getAttribVal2() {
        return attribVal2;
    }

    /**
     * ODH_CODE_MANAGE.ATTRIB_VAL2
     *
     * @param attribVal2 the value for ODH_CODE_MANAGE.ATTRIB_VAL2
     */
    public void setAttribVal2(String attribVal2) {
        this.attribVal2 = attribVal2;
    }

    /**
     * ODH_CODE_MANAGE.ATTRIB_EXPLA2
     *
     * @return the value of ODH_CODE_MANAGE.ATTRIB_EXPLA2
     */
    public String getAttribExpla2() {
        return attribExpla2;
    }

    /**
     * ODH_CODE_MANAGE.ATTRIB_EXPLA2
     *
     * @param attribExpla2 the value for ODH_CODE_MANAGE.ATTRIB_EXPLA2
     */
    public void setAttribExpla2(String attribExpla2) {
        this.attribExpla2 = attribExpla2;
    }

    /**
     * ODH_CODE_MANAGE.ATTRIB_VAL3
     *
     * @return the value of ODH_CODE_MANAGE.ATTRIB_VAL3
     */
    public String getAttribVal3() {
        return attribVal3;
    }

    /**
     * ODH_CODE_MANAGE.ATTRIB_VAL3
     *
     * @param attribVal3 the value for ODH_CODE_MANAGE.ATTRIB_VAL3
     */
    public void setAttribVal3(String attribVal3) {
        this.attribVal3 = attribVal3;
    }

    /**
     * ODH_CODE_MANAGE.ATTRIB_EXPLA3
     *
     * @return the value of ODH_CODE_MANAGE.ATTRIB_EXPLA3
     */
    public String getAttribExpla3() {
        return attribExpla3;
    }

    /**
     * ODH_CODE_MANAGE.ATTRIB_EXPLA3
     *
     * @param attribExpla3 the value for ODH_CODE_MANAGE.ATTRIB_EXPLA3
     */
    public void setAttribExpla3(String attribExpla3) {
        this.attribExpla3 = attribExpla3;
    }

    /**
     * ODH_CODE_MANAGE.ATTRIB_EXPLA_SHORT
     *
     * @return the value of ODH_CODE_MANAGE.ATTRIB_EXPLA_SHORT
     */
    public String getAttribExplaShort() {
        return attribExplaShort;
    }

    /**
     * ODH_CODE_MANAGE.ATTRIB_EXPLA_SHORT
     *
     * @param attribExplaShort the value for ODH_CODE_MANAGE.ATTRIB_EXPLA_SHORT
     */
    public void setAttribExplaShort(String attribExplaShort) {
        this.attribExplaShort = attribExplaShort;
    }

    /**
     * ODH_CODE_MANAGE.LOGIN_NO
     *
     * @return the value of ODH_CODE_MANAGE.LOGIN_NO
     */
    public String getLoginNo() {
        return loginNo;
    }

    /**
     * ODH_CODE_MANAGE.LOGIN_NO
     *
     * @param loginNo the value for ODH_CODE_MANAGE.LOGIN_NO
     */
    public void setLoginNo(String loginNo) {
        this.loginNo = loginNo;
    }

    /**
     * ODH_CODE_MANAGE.LOGIN_IP
     *
     * @return the value of ODH_CODE_MANAGE.LOGIN_IP
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * ODH_CODE_MANAGE.LOGIN_IP
     *
     * @param loginIp the value for ODH_CODE_MANAGE.LOGIN_IP
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp;
    }

    /**
     * ODH_CODE_MANAGE.REC_INSERT_TIME
     *
     * @return the value of ODH_CODE_MANAGE.REC_INSERT_TIME
     */
    public Date getRecInsertTime() {
        return recInsertTime;
    }

    /**
     * ODH_CODE_MANAGE.REC_INSERT_TIME
     *
     * @param recInsertTime the value for ODH_CODE_MANAGE.REC_INSERT_TIME
     */
    public void setRecInsertTime(Date recInsertTime) {
        this.recInsertTime = recInsertTime;
    }

    /**
     * ODH_CODE_MANAGE.DELETE_STATE
     *
     * @return the value of ODH_CODE_MANAGE.DELETE_STATE
     */
    public String getDeleteState() {
        return deleteState;
    }

    /**
     * ODH_CODE_MANAGE.DELETE_STATE
     *
     * @param deleteState the value for ODH_CODE_MANAGE.DELETE_STATE
     */
    public void setDeleteState(String deleteState) {
        this.deleteState = deleteState;
    }

    /**
     * ODH_CODE_MANAGE.UPDATE_NO
     *
     * @return the value of ODH_CODE_MANAGE.UPDATE_NO
     */
    public String getUpdateNo() {
        return updateNo;
    }

    /**
     * ODH_CODE_MANAGE.UPDATE_NO
     *
     * @param updateNo the value for ODH_CODE_MANAGE.UPDATE_NO
     */
    public void setUpdateNo(String updateNo) {
        this.updateNo = updateNo;
    }

    /**
     * ODH_CODE_MANAGE.UPDATE_IP
     *
     * @return the value of ODH_CODE_MANAGE.UPDATE_IP
     */
    public String getUpdateIp() {
        return updateIp;
    }

    /**
     * ODH_CODE_MANAGE.UPDATE_IP
     *
     * @param updateIp the value for ODH_CODE_MANAGE.UPDATE_IP
     */
    public void setUpdateIp(String updateIp) {
        this.updateIp = updateIp;
    }

    /**
     * ODH_CODE_MANAGE.REC_UPDATE_TIME
     *
     * @return the value of ODH_CODE_MANAGE.REC_UPDATE_TIME
     */
    public Date getRecUpdateTime() {
        return recUpdateTime;
    }

    /**
     * ODH_CODE_MANAGE.REC_UPDATE_TIME
     *
     * @param recUpdateTime the value for ODH_CODE_MANAGE.REC_UPDATE_TIME
     */
    public void setRecUpdateTime(Date recUpdateTime) {
        this.recUpdateTime = recUpdateTime;
    }

    /**
     * ODH_CODE_MANAGE
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", recNo=").append(recNo);
        sb.append(", attribId=").append(attribId);
        sb.append(", attribName=").append(attribName);
        sb.append(", attribVal=").append(attribVal);
        sb.append(", attribExpla=").append(attribExpla);
        sb.append(", attribVal2=").append(attribVal2);
        sb.append(", attribExpla2=").append(attribExpla2);
        sb.append(", attribVal3=").append(attribVal3);
        sb.append(", attribExpla3=").append(attribExpla3);
        sb.append(", attribExplaShort=").append(attribExplaShort);
        sb.append(", loginNo=").append(loginNo);
        sb.append(", loginIp=").append(loginIp);
        sb.append(", recInsertTime=").append(recInsertTime);
        sb.append(", deleteState=").append(deleteState);
        sb.append(", updateNo=").append(updateNo);
        sb.append(", updateIp=").append(updateIp);
        sb.append(", recUpdateTime=").append(recUpdateTime);
        sb.append("]");
        return sb.toString();
    }
}