/**
  * Copyright &copy; 2012-2017 <a href="">GLAD</a> All rights reserved.
 */
package com.glad.entity;

import com.glad.component.AbstractDto;

/**
 *
 * This model class was generated by MyBatis Generator.
 * TABLE : ODH_MODL_INFO
 *  2017.08.08 14:01:16
 */
public class OdhModlInfo extends AbstractDto {
    /**
     *   模块ID
     * MODEL_ID
     */
    private String modelId;

    /**
     *   父模块ID
     * PARENT_MODEL_ID
     */
    private String parentModelId;

    /**
     *   模块URL
     * MODEL_URL
     */
    private String modelUrl;

    /**
     *   模块名称
     * MODEL_NAME
     */
    private String modelName;

    /**
     *   模块说明
     * MODEL_INFO
     */
    private String modelInfo;

    /**
     *   层数
     * LAYER_NO
     */
    private Integer layerNo;

    /**
     *   显示顺序
     * DISPLAY_ORDER
     */
    private Integer displayOrder;

    /**
     * ODH_MODL_INFO.MODEL_ID
     *
     * @return the value of ODH_MODL_INFO.MODEL_ID
     */
    public String getModelId() {
        return modelId;
    }

    /**
     * ODH_MODL_INFO.MODEL_ID
     *
     * @param modelId the value for ODH_MODL_INFO.MODEL_ID
     */
    public void setModelId(String modelId) {
        this.modelId = modelId;
    }

    /**
     * ODH_MODL_INFO.PARENT_MODEL_ID
     *
     * @return the value of ODH_MODL_INFO.PARENT_MODEL_ID
     */
    public String getParentModelId() {
        return parentModelId;
    }

    /**
     * ODH_MODL_INFO.PARENT_MODEL_ID
     *
     * @param parentModelId the value for ODH_MODL_INFO.PARENT_MODEL_ID
     */
    public void setParentModelId(String parentModelId) {
        this.parentModelId = parentModelId;
    }

    /**
     * ODH_MODL_INFO.MODEL_URL
     *
     * @return the value of ODH_MODL_INFO.MODEL_URL
     */
    public String getModelUrl() {
        return modelUrl;
    }

    /**
     * ODH_MODL_INFO.MODEL_URL
     *
     * @param modelUrl the value for ODH_MODL_INFO.MODEL_URL
     */
    public void setModelUrl(String modelUrl) {
        this.modelUrl = modelUrl;
    }

    /**
     * ODH_MODL_INFO.MODEL_NAME
     *
     * @return the value of ODH_MODL_INFO.MODEL_NAME
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * ODH_MODL_INFO.MODEL_NAME
     *
     * @param modelName the value for ODH_MODL_INFO.MODEL_NAME
     */
    public void setModelName(String modelName) {
        this.modelName = modelName;
    }

    /**
     * ODH_MODL_INFO.MODEL_INFO
     *
     * @return the value of ODH_MODL_INFO.MODEL_INFO
     */
    public String getModelInfo() {
        return modelInfo;
    }

    /**
     * ODH_MODL_INFO.MODEL_INFO
     *
     * @param modelInfo the value for ODH_MODL_INFO.MODEL_INFO
     */
    public void setModelInfo(String modelInfo) {
        this.modelInfo = modelInfo;
    }

    /**
     * ODH_MODL_INFO.LAYER_NO
     *
     * @return the value of ODH_MODL_INFO.LAYER_NO
     */
    public Integer getLayerNo() {
        return layerNo;
    }

    /**
     * ODH_MODL_INFO.LAYER_NO
     *
     * @param layerNo the value for ODH_MODL_INFO.LAYER_NO
     */
    public void setLayerNo(Integer layerNo) {
        this.layerNo = layerNo;
    }

    /**
     * ODH_MODL_INFO.DISPLAY_ORDER
     *
     * @return the value of ODH_MODL_INFO.DISPLAY_ORDER
     */
    public Integer getDisplayOrder() {
        return displayOrder;
    }

    /**
     * ODH_MODL_INFO.DISPLAY_ORDER
     *
     * @param displayOrder the value for ODH_MODL_INFO.DISPLAY_ORDER
     */
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    /**
     * ODH_MODL_INFO
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", modelId=").append(modelId);
        sb.append(", parentModelId=").append(parentModelId);
        sb.append(", modelUrl=").append(modelUrl);
        sb.append(", modelName=").append(modelName);
        sb.append(", modelInfo=").append(modelInfo);
        sb.append(", layerNo=").append(layerNo);
        sb.append(", displayOrder=").append(displayOrder);
        sb.append("]");
        return sb.toString();
    }
}