/**
  * Copyright &copy; 2012-2017 <a href="">GLAD</a> All rights reserved.
 */
package com.glad.entity;

import com.glad.component.AbstractDto;
import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This model class was generated by MyBatis Generator.
 * TABLE : ODH_WKTM_MANAGE
 *  2017.08.08 14:00:42
 */
public class OdhWktmManage extends AbstractDto {
    /**
     *   记录番号
     * REC_NO
     */
    private Integer recNo;

    /**
     *   工号
     * USER_NO
     */
    private String userNo;

    /**
     *   工时年月日
     * REG_YMD
     */
    private Date regYmd;

    /**
     *   工时类型
     * WKTM_TYPE
     */
    private String wktmType;

    /**
     *   工时子类型
     * WKTM_SUBTYPE
     */
    private String wktmSubtype;

    /**
     *   项目阶段
     * PROJECT_STAGE
     */
    private String projectStage;

    /**
     *   工时登记开始时间
     * WKTM_START_YMDHM
     */
    private Date wktmStartYmdhm;

    /**
     *   工时登记结束时间
     * WKTM_END_YMDHM
     */
    private Date wktmEndYmdhm;

    /**
     *   工时数
     * WKTM_TIMES
     */
    private BigDecimal wktmTimes;

    /**
     *   备注
     * MEMO
     */
    private String memo;

    /**
     *   亲子区分
     * SUB_FLG
     */
    private String subFlg;

    /**
     *   拆分区分
     * SEPT_FLG
     */
    private String septFlg;

    /**
     * ODH_WKTM_MANAGE.REC_NO
     *
     * @return the value of ODH_WKTM_MANAGE.REC_NO
     */
    public Integer getRecNo() {
        return recNo;
    }

    /**
     * ODH_WKTM_MANAGE.REC_NO
     *
     * @param recNo the value for ODH_WKTM_MANAGE.REC_NO
     */
    public void setRecNo(Integer recNo) {
        this.recNo = recNo;
    }

    /**
     * ODH_WKTM_MANAGE.USER_NO
     *
     * @return the value of ODH_WKTM_MANAGE.USER_NO
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * ODH_WKTM_MANAGE.USER_NO
     *
     * @param userNo the value for ODH_WKTM_MANAGE.USER_NO
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo;
    }

    /**
     * ODH_WKTM_MANAGE.REG_YMD
     *
     * @return the value of ODH_WKTM_MANAGE.REG_YMD
     */
    public Date getRegYmd() {
        return regYmd;
    }

    /**
     * ODH_WKTM_MANAGE.REG_YMD
     *
     * @param regYmd the value for ODH_WKTM_MANAGE.REG_YMD
     */
    public void setRegYmd(Date regYmd) {
        this.regYmd = regYmd;
    }

    /**
     * ODH_WKTM_MANAGE.WKTM_TYPE
     *
     * @return the value of ODH_WKTM_MANAGE.WKTM_TYPE
     */
    public String getWktmType() {
        return wktmType;
    }

    /**
     * ODH_WKTM_MANAGE.WKTM_TYPE
     *
     * @param wktmType the value for ODH_WKTM_MANAGE.WKTM_TYPE
     */
    public void setWktmType(String wktmType) {
        this.wktmType = wktmType;
    }

    /**
     * ODH_WKTM_MANAGE.WKTM_SUBTYPE
     *
     * @return the value of ODH_WKTM_MANAGE.WKTM_SUBTYPE
     */
    public String getWktmSubtype() {
        return wktmSubtype;
    }

    /**
     * ODH_WKTM_MANAGE.WKTM_SUBTYPE
     *
     * @param wktmSubtype the value for ODH_WKTM_MANAGE.WKTM_SUBTYPE
     */
    public void setWktmSubtype(String wktmSubtype) {
        this.wktmSubtype = wktmSubtype;
    }

    /**
     * ODH_WKTM_MANAGE.PROJECT_STAGE
     *
     * @return the value of ODH_WKTM_MANAGE.PROJECT_STAGE
     */
    public String getProjectStage() {
        return projectStage;
    }

    /**
     * ODH_WKTM_MANAGE.PROJECT_STAGE
     *
     * @param projectStage the value for ODH_WKTM_MANAGE.PROJECT_STAGE
     */
    public void setProjectStage(String projectStage) {
        this.projectStage = projectStage;
    }

    /**
     * ODH_WKTM_MANAGE.WKTM_START_YMDHM
     *
     * @return the value of ODH_WKTM_MANAGE.WKTM_START_YMDHM
     */
    public Date getWktmStartYmdhm() {
        return wktmStartYmdhm;
    }

    /**
     * ODH_WKTM_MANAGE.WKTM_START_YMDHM
     *
     * @param wktmStartYmdhm the value for ODH_WKTM_MANAGE.WKTM_START_YMDHM
     */
    public void setWktmStartYmdhm(Date wktmStartYmdhm) {
        this.wktmStartYmdhm = wktmStartYmdhm;
    }

    /**
     * ODH_WKTM_MANAGE.WKTM_END_YMDHM
     *
     * @return the value of ODH_WKTM_MANAGE.WKTM_END_YMDHM
     */
    public Date getWktmEndYmdhm() {
        return wktmEndYmdhm;
    }

    /**
     * ODH_WKTM_MANAGE.WKTM_END_YMDHM
     *
     * @param wktmEndYmdhm the value for ODH_WKTM_MANAGE.WKTM_END_YMDHM
     */
    public void setWktmEndYmdhm(Date wktmEndYmdhm) {
        this.wktmEndYmdhm = wktmEndYmdhm;
    }

    /**
     * ODH_WKTM_MANAGE.WKTM_TIMES
     *
     * @return the value of ODH_WKTM_MANAGE.WKTM_TIMES
     */
    public BigDecimal getWktmTimes() {
        return wktmTimes;
    }

    /**
     * ODH_WKTM_MANAGE.WKTM_TIMES
     *
     * @param wktmTimes the value for ODH_WKTM_MANAGE.WKTM_TIMES
     */
    public void setWktmTimes(BigDecimal wktmTimes) {
        this.wktmTimes = wktmTimes;
    }

    /**
     * ODH_WKTM_MANAGE.MEMO
     *
     * @return the value of ODH_WKTM_MANAGE.MEMO
     */
    public String getMemo() {
        return memo;
    }

    /**
     * ODH_WKTM_MANAGE.MEMO
     *
     * @param memo the value for ODH_WKTM_MANAGE.MEMO
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * ODH_WKTM_MANAGE.SUB_FLG
     *
     * @return the value of ODH_WKTM_MANAGE.SUB_FLG
     */
    public String getSubFlg() {
        return subFlg;
    }

    /**
     * ODH_WKTM_MANAGE.SUB_FLG
     *
     * @param subFlg the value for ODH_WKTM_MANAGE.SUB_FLG
     */
    public void setSubFlg(String subFlg) {
        this.subFlg = subFlg;
    }

    /**
     * ODH_WKTM_MANAGE.SEPT_FLG
     *
     * @return the value of ODH_WKTM_MANAGE.SEPT_FLG
     */
    public String getSeptFlg() {
        return septFlg;
    }

    /**
     * ODH_WKTM_MANAGE.SEPT_FLG
     *
     * @param septFlg the value for ODH_WKTM_MANAGE.SEPT_FLG
     */
    public void setSeptFlg(String septFlg) {
        this.septFlg = septFlg;
    }

    /**
     * ODH_WKTM_MANAGE
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", recNo=").append(recNo);
        sb.append(", userNo=").append(userNo);
        sb.append(", regYmd=").append(regYmd);
        sb.append(", wktmType=").append(wktmType);
        sb.append(", wktmSubtype=").append(wktmSubtype);
        sb.append(", projectStage=").append(projectStage);
        sb.append(", wktmStartYmdhm=").append(wktmStartYmdhm);
        sb.append(", wktmEndYmdhm=").append(wktmEndYmdhm);
        sb.append(", wktmTimes=").append(wktmTimes);
        sb.append(", memo=").append(memo);
        sb.append(", subFlg=").append(subFlg);
        sb.append(", septFlg=").append(septFlg);
        sb.append("]");
        return sb.toString();
    }
}