/**
  * copyright -------TODO -------
 */
package com.glad.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.glad.component.AbstractDto;

/**
 * This class was generated by MyBatis Generator. TABLE : ODH_WKTM_MANAGE 2017.07.28 10:17:19
 */
public class OdhWktmManage extends AbstractDto {
	/**
	 * USER_NO 工号
	 */
	private String userNo;

	/**
	 * REC_NO 记录番号
	 */
	private Integer recNo;

	/**
	 * REG_YMD 工时年月日
	 */
	private Date regYmd;

	/**
	 * WKTM_TYPE 工时类型
	 */
	private String wktmType;

	/**
	 * WKTM_SUBTYPE 工时子类型
	 */
	private String wktmSubtype;

	/**
	 * PROJECT_STAGE 项目阶段
	 */
	private String projectStage;

	/**
	 * WKTM_START_YMDHM 工时登记开始时间
	 */
	private Date wktmStartYmdhm;

	/**
	 * WKTM_END_YMDHM 工时登记结束时间
	 */
	private Date wktmEndYmdhm;

	/**
	 * WKTM_TIMES 工时数
	 */
	private BigDecimal wktmTimes;

	/**
	 * MEMO 备注
	 */
	private String memo;

	/**
	 * SUB_FLG 亲子区分
	 */
	private String subFlg;

	/**
	 * SEPT_FLG 拆分区分
	 */
	private String septFlg;

	/**
	 * LOGIN_NO 登录者工号
	 */
	private String loginNo;

	/**
	 * LOGIN_IP 登录者IP
	 */
	private String loginIp;

	/**
	 * REC_INSERT_TIME 记录作成时间
	 */
	private Date recInsertTime;

	/**
	 * DELETE_STATE 删除状态位
	 */
	private String deleteState;

	/**
	 * UPDATE_NO 更新者工号
	 */
	private String updateNo;

	/**
	 * UPDATE_IP 更新者IP
	 */
	private String updateIp;

	/**
	 * REC_UPDATE_TIME 记录更新时间
	 */
	private Date recUpdateTime;

	/**
	 * ODH_WKTM_MANAGE.USER_NO
	 *
	 * @return the value of ODH_WKTM_MANAGE.USER_NO
	 */
	public String getUserNo() {
		return userNo;
	}

	/**
	 * ODH_WKTM_MANAGE.USER_NO
	 *
	 * @param userNo the value for ODH_WKTM_MANAGE.USER_NO
	 */
	public void setUserNo(String userNo) {
		this.userNo = userNo;
	}

	/**
	 * ODH_WKTM_MANAGE.REC_NO
	 *
	 * @return the value of ODH_WKTM_MANAGE.REC_NO
	 */
	public Integer getRecNo() {
		return recNo;
	}

	/**
	 * ODH_WKTM_MANAGE.REC_NO
	 *
	 * @param recNo the value for ODH_WKTM_MANAGE.REC_NO
	 */
	public void setRecNo(Integer recNo) {
		this.recNo = recNo;
	}

	/**
	 * ODH_WKTM_MANAGE.REG_YMD
	 *
	 * @return the value of ODH_WKTM_MANAGE.REG_YMD
	 */
	public Date getRegYmd() {
		return regYmd;
	}

	/**
	 * ODH_WKTM_MANAGE.REG_YMD
	 *
	 * @param regYmd the value for ODH_WKTM_MANAGE.REG_YMD
	 */
	public void setRegYmd(Date regYmd) {
		this.regYmd = regYmd;
	}

	/**
	 * ODH_WKTM_MANAGE.WKTM_TYPE
	 *
	 * @return the value of ODH_WKTM_MANAGE.WKTM_TYPE
	 */
	public String getWktmType() {
		return wktmType;
	}

	/**
	 * ODH_WKTM_MANAGE.WKTM_TYPE
	 *
	 * @param wktmType the value for ODH_WKTM_MANAGE.WKTM_TYPE
	 */
	public void setWktmType(String wktmType) {
		this.wktmType = wktmType;
	}

	/**
	 * ODH_WKTM_MANAGE.WKTM_SUBTYPE
	 *
	 * @return the value of ODH_WKTM_MANAGE.WKTM_SUBTYPE
	 */
	public String getWktmSubtype() {
		return wktmSubtype;
	}

	/**
	 * ODH_WKTM_MANAGE.WKTM_SUBTYPE
	 *
	 * @param wktmSubtype the value for ODH_WKTM_MANAGE.WKTM_SUBTYPE
	 */
	public void setWktmSubtype(String wktmSubtype) {
		this.wktmSubtype = wktmSubtype;
	}

	/**
	 * ODH_WKTM_MANAGE.PROJECT_STAGE
	 *
	 * @return the value of ODH_WKTM_MANAGE.PROJECT_STAGE
	 */
	public String getProjectStage() {
		return projectStage;
	}

	/**
	 * ODH_WKTM_MANAGE.PROJECT_STAGE
	 *
	 * @param projectStage the value for ODH_WKTM_MANAGE.PROJECT_STAGE
	 */
	public void setProjectStage(String projectStage) {
		this.projectStage = projectStage;
	}

	/**
	 * ODH_WKTM_MANAGE.WKTM_START_YMDHM
	 *
	 * @return the value of ODH_WKTM_MANAGE.WKTM_START_YMDHM
	 */
	public Date getWktmStartYmdhm() {
		return wktmStartYmdhm;
	}

	/**
	 * ODH_WKTM_MANAGE.WKTM_START_YMDHM
	 *
	 * @param wktmStartYmdhm the value for ODH_WKTM_MANAGE.WKTM_START_YMDHM
	 */
	public void setWktmStartYmdhm(Date wktmStartYmdhm) {
		this.wktmStartYmdhm = wktmStartYmdhm;
	}

	/**
	 * ODH_WKTM_MANAGE.WKTM_END_YMDHM
	 *
	 * @return the value of ODH_WKTM_MANAGE.WKTM_END_YMDHM
	 */
	public Date getWktmEndYmdhm() {
		return wktmEndYmdhm;
	}

	/**
	 * ODH_WKTM_MANAGE.WKTM_END_YMDHM
	 *
	 * @param wktmEndYmdhm the value for ODH_WKTM_MANAGE.WKTM_END_YMDHM
	 */
	public void setWktmEndYmdhm(Date wktmEndYmdhm) {
		this.wktmEndYmdhm = wktmEndYmdhm;
	}

	/**
	 * ODH_WKTM_MANAGE.WKTM_TIMES
	 *
	 * @return the value of ODH_WKTM_MANAGE.WKTM_TIMES
	 */
	public BigDecimal getWktmTimes() {
		return wktmTimes;
	}

	/**
	 * ODH_WKTM_MANAGE.WKTM_TIMES
	 *
	 * @param wktmTimes the value for ODH_WKTM_MANAGE.WKTM_TIMES
	 */
	public void setWktmTimes(BigDecimal wktmTimes) {
		this.wktmTimes = wktmTimes;
	}

	/**
	 * ODH_WKTM_MANAGE.MEMO
	 *
	 * @return the value of ODH_WKTM_MANAGE.MEMO
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * ODH_WKTM_MANAGE.MEMO
	 *
	 * @param memo the value for ODH_WKTM_MANAGE.MEMO
	 */
	public void setMemo(String memo) {
		this.memo = memo;
	}

	/**
	 * ODH_WKTM_MANAGE.SUB_FLG
	 *
	 * @return the value of ODH_WKTM_MANAGE.SUB_FLG
	 */
	public String getSubFlg() {
		return subFlg;
	}

	/**
	 * ODH_WKTM_MANAGE.SUB_FLG
	 *
	 * @param subFlg the value for ODH_WKTM_MANAGE.SUB_FLG
	 */
	public void setSubFlg(String subFlg) {
		this.subFlg = subFlg;
	}

	/**
	 * ODH_WKTM_MANAGE.SEPT_FLG
	 *
	 * @return the value of ODH_WKTM_MANAGE.SEPT_FLG
	 */
	public String getSeptFlg() {
		return septFlg;
	}

	/**
	 * ODH_WKTM_MANAGE.SEPT_FLG
	 *
	 * @param septFlg the value for ODH_WKTM_MANAGE.SEPT_FLG
	 */
	public void setSeptFlg(String septFlg) {
		this.septFlg = septFlg;
	}

	/**
	 * ODH_WKTM_MANAGE.LOGIN_NO
	 *
	 * @return the value of ODH_WKTM_MANAGE.LOGIN_NO
	 */
	public String getLoginNo() {
		return loginNo;
	}

	/**
	 * ODH_WKTM_MANAGE.LOGIN_NO
	 *
	 * @param loginNo the value for ODH_WKTM_MANAGE.LOGIN_NO
	 */
	public void setLoginNo(String loginNo) {
		this.loginNo = loginNo;
	}

	/**
	 * ODH_WKTM_MANAGE.LOGIN_IP
	 *
	 * @return the value of ODH_WKTM_MANAGE.LOGIN_IP
	 */
	public String getLoginIp() {
		return loginIp;
	}

	/**
	 * ODH_WKTM_MANAGE.LOGIN_IP
	 *
	 * @param loginIp the value for ODH_WKTM_MANAGE.LOGIN_IP
	 */
	public void setLoginIp(String loginIp) {
		this.loginIp = loginIp;
	}

	/**
	 * ODH_WKTM_MANAGE.REC_INSERT_TIME
	 *
	 * @return the value of ODH_WKTM_MANAGE.REC_INSERT_TIME
	 */
	public Date getRecInsertTime() {
		return recInsertTime;
	}

	/**
	 * ODH_WKTM_MANAGE.REC_INSERT_TIME
	 *
	 * @param recInsertTime the value for ODH_WKTM_MANAGE.REC_INSERT_TIME
	 */
	public void setRecInsertTime(Date recInsertTime) {
		this.recInsertTime = recInsertTime;
	}

	/**
	 * ODH_WKTM_MANAGE.DELETE_STATE
	 *
	 * @return the value of ODH_WKTM_MANAGE.DELETE_STATE
	 */
	public String getDeleteState() {
		return deleteState;
	}

	/**
	 * ODH_WKTM_MANAGE.DELETE_STATE
	 *
	 * @param deleteState the value for ODH_WKTM_MANAGE.DELETE_STATE
	 */
	public void setDeleteState(String deleteState) {
		this.deleteState = deleteState;
	}

	/**
	 * ODH_WKTM_MANAGE.UPDATE_NO
	 *
	 * @return the value of ODH_WKTM_MANAGE.UPDATE_NO
	 */
	public String getUpdateNo() {
		return updateNo;
	}

	/**
	 * ODH_WKTM_MANAGE.UPDATE_NO
	 *
	 * @param updateNo the value for ODH_WKTM_MANAGE.UPDATE_NO
	 */
	public void setUpdateNo(String updateNo) {
		this.updateNo = updateNo;
	}

	/**
	 * ODH_WKTM_MANAGE.UPDATE_IP
	 *
	 * @return the value of ODH_WKTM_MANAGE.UPDATE_IP
	 */
	public String getUpdateIp() {
		return updateIp;
	}

	/**
	 * ODH_WKTM_MANAGE.UPDATE_IP
	 *
	 * @param updateIp the value for ODH_WKTM_MANAGE.UPDATE_IP
	 */
	public void setUpdateIp(String updateIp) {
		this.updateIp = updateIp;
	}

	/**
	 * ODH_WKTM_MANAGE.REC_UPDATE_TIME
	 *
	 * @return the value of ODH_WKTM_MANAGE.REC_UPDATE_TIME
	 */
	public Date getRecUpdateTime() {
		return recUpdateTime;
	}

	/**
	 * ODH_WKTM_MANAGE.REC_UPDATE_TIME
	 *
	 * @param recUpdateTime the value for ODH_WKTM_MANAGE.REC_UPDATE_TIME
	 */
	public void setRecUpdateTime(Date recUpdateTime) {
		this.recUpdateTime = recUpdateTime;
	}

	/**
	 * ODH_WKTM_MANAGE
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", userNo=").append(userNo);
		sb.append(", recNo=").append(recNo);
		sb.append(", regYmd=").append(regYmd);
		sb.append(", wktmType=").append(wktmType);
		sb.append(", wktmSubtype=").append(wktmSubtype);
		sb.append(", projectStage=").append(projectStage);
		sb.append(", wktmStartYmdhm=").append(wktmStartYmdhm);
		sb.append(", wktmEndYmdhm=").append(wktmEndYmdhm);
		sb.append(", wktmTimes=").append(wktmTimes);
		sb.append(", memo=").append(memo);
		sb.append(", subFlg=").append(subFlg);
		sb.append(", septFlg=").append(septFlg);
		sb.append(", loginNo=").append(loginNo);
		sb.append(", loginIp=").append(loginIp);
		sb.append(", recInsertTime=").append(recInsertTime);
		sb.append(", deleteState=").append(deleteState);
		sb.append(", updateNo=").append(updateNo);
		sb.append(", updateIp=").append(updateIp);
		sb.append(", recUpdateTime=").append(recUpdateTime);
		sb.append("]");
		return sb.toString();
	}
}